server:
  port: 8006

spring:
  application:
    name: jmj-config-nat-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/center-config/
      label: master
