server:
  port: 8001

spring:
  application:
    name: jmj-gateway

zuul:
  prefix: /gateway
  retryable: false
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 5000
    max-total-connections: 5000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

# token过滤白名单（以下接口不校验token，直接放行）
tokenWhiteList:
  "/gateway/jmj-provider-player/register, \
   /gateway/jmj-provider-player/login, \
   /gateway/jmj-provider-dice/v2/api-docs, \
   /gateway/jmj-provider-hall/v2/api-docs, \
   /gateway/jmj-provider-majiang/v2/api-docs, \
   /gateway/jmj-provider-player/v2/api-docs, \
   /gateway/jmj-provider-room/v2/api-docs"

