server:
  port: 8002

spring:
  application:
    name: jmj-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wllfengshu/jmj
          search-paths: center-config
          username: wllfengshu@163.com
          password: 1111111
