server:
  port: 8001

spring:
  application:
    name: gateway-server
  profiles:
    active: native
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true